freebsd_instance:
  image: freebsd-13-2-release-amd64
  cpu: 4

env:
  MAKE_FLAGS: -j 4

task:
  install_script:
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    - ASSUME_ALWAYS_YES=yes pkg bootstrap -f
    - pkg install -y gmp mpfr boost-libs cmake ninja py311-pytest py311-pip py311-wheel

  build_script:
    - fetch "https://github.com/CGAL/cgal/releases/download/v5.6/CGAL-5.6.tar.xz" -o CGAL-5.6.tar.xz
    - fetch "https://gitlab.com/SFCGAL/SFCGAL/-/archive/master/SFCGAL-master.tar.gz" -o SFCGAL.tar.gz
    - tar xzf SFCGAL.tar.gz
    - cd SFCGAL-master  
    - tar xJf ../CGAL-5.6.tar.xz
    - cmake -GNinja -S . -B build -DCGAL_DIR=CGAL-5.6
    - cmake --build build
    - cmake --install build
    - cd ..  
    - env CFLAGS=-I/usr/local/include python3.11 setup.py build install
    - ls tests/test_* | xargs pytest-3.11
